'use strict';
const $=s=>document.querySelector(s);
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
window.afoc={paused:motionQuery.matches,pulse:0,scroll:0};
const motion=$('#motion');
function updateMotion(){motion.textContent=window.afoc.paused?'▶':'Ⅱ';motion.setAttribute('aria-pressed',String(window.afoc.paused));motion.setAttribute('aria-label',window.afoc.paused?'Resume animation':'Pause animation');document.body.classList.toggle('motion-paused',window.afoc.paused)}
updateMotion();motion.addEventListener('click',()=>{window.afoc.paused=!window.afoc.paused;updateMotion()});
motionQuery.addEventListener('change',e=>{window.afoc.paused=e.matches;updateMotion()});
$('#pulse').addEventListener('click',()=>{window.afoc.replayTime=window.afocSceneTime||0;if(window.afoc.paused){window.afoc.paused=false;updateMotion()}$('#pulse').firstChild.textContent='Light is taking shape ';setTimeout(()=>{$('#pulse').firstChild.textContent='Replay the formation '},6700)});
const menu=$('#menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');$('#mobile-nav').hidden=!open});
$('#mobile-nav').querySelectorAll('a,button').forEach(a=>a.addEventListener('click',()=>{$('#mobile-nav').hidden=true;menu.setAttribute('aria-expanded','false')}));
let scrollScheduled=false;function updateScroll(){const y=scrollY,hero=$('.hero').offsetHeight,j=$('#journey'),p=Math.max(0,Math.min(1,(y-hero)/(j.offsetHeight-innerHeight)));window.afoc.scroll=y;window.afoc.journey=p;window.afoc.hero=hero;window.afoc.journeyEnd=hero+j.offsetHeight;$('#page-progress').style.height=(y/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100)+'%';const fade=(start,end)=>Math.min(1,Math.max(0,(p-start)*12))*Math.min(1,Math.max(0,(end-p)*12));$('#chapter-one').style.opacity=String(fade(-.02,.24));$('#chapter-two').style.opacity=String(fade(.26,.53));$('#chapter-three').style.opacity=String(fade(.56,.72));$('#chapter-three').style.pointerEvents=p>.56&&p<.72?'auto':'none';$('#chapter-four').style.opacity=String(fade(.76,1.14));$('#city-pulse').disabled=!(p>.56&&p<.72);$('#chapter-progress').style.width=(p*100)+'%';$('#chapter-num').textContent=p>.76?'04':p>.56?'03':p>.26?'02':'01';$('#travel-stage').textContent=p>.76?'ONE CONNECTED PLANET':p>.56?'LEAVING THE SKYLINE':p>.26?'DUBAI / DRAWN IN LIGHT':'TRAVELLING WITH THE LIGHT';$('#travel-distance').textContent=String(Math.round(p*100)).padStart(3,'0');scrollScheduled=false}
addEventListener('scroll',()=>{if(!scrollScheduled){requestAnimationFrame(updateScroll);scrollScheduled=true}},{passive:true});addEventListener('resize',updateScroll);updateScroll();
$('#city-pulse').addEventListener('click',()=>{window.afoc.pulse=performance.now();$('#city-pulse').firstChild.textContent='The connection is alive ';setTimeout(()=>{$('#city-pulse').firstChild.textContent='Illuminate the connection '},3500)});
document.querySelectorAll('.solution').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.solution').forEach(o=>{if(o!==d)o.open=false})}));
const apps=[{title:'The city.<br>Connected.',copy:'Homes, destinations, and the spaces in between. Imagine a fiber network woven into the life of a city.',topic:'City connectivity',point:[514,82]},{title:'The digital world.<br>Made physical.',copy:'Behind the cloud are real connections. Explore the pathways between data environments, information, and the people who depend on them.',topic:'Data environments',point:[656,192]},{title:'More than a place.<br>A possibility.',copy:'A workplace. A campus. A new destination. Think about the connections your people need today—and the spaces you want to create tomorrow.',topic:'Business connectivity',point:[352,160]}];
const tabs=[...document.querySelectorAll('[data-app]')];function setApp(i){tabs.forEach((b,j)=>{b.setAttribute('aria-selected',String(j===i));b.tabIndex=j===i?0:-1});const a=apps[i];$('#app-panel').setAttribute('aria-labelledby',tabs[i].id);$('#app-num').textContent=`0${i+1} / 03`;$('#app-title').innerHTML=a.title;$('#app-copy').textContent=a.copy;$('#app-brief').dataset.topic=a.topic;['#map-marker','.marker-halo'].forEach(s=>{$(s).setAttribute('cx',a.point[0]);$(s).setAttribute('cy',a.point[1])})}tabs.forEach((b,i)=>{b.addEventListener('click',()=>setApp(i));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setApp(n);tabs[n].focus()}})});
const dialog=$('#brief-dialog');let previousFocus;document.querySelectorAll('[data-brief]').forEach(b=>b.addEventListener('click',()=>{previousFocus=b;if(b.dataset.topic)$('#focus').value=b.dataset.topic;$('#form-status').textContent='';dialog.showModal();document.body.classList.add('modal-open')}));function closeBrief(){dialog.close()}$('.dialog-close').addEventListener('click',closeBrief);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeBrief()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');previousFocus?.focus()});$('#brief-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),content=`AFOC — PROJECT BRIEF\nArabian Fiber Optics\n\nName: ${f.get('name')}\nEmail: ${f.get('email')}\nFocus: ${f.get('focus')}\n\nProject overview\n${f.get('message')}\n\nPrepared from the AFOC website concept. This brief has not been sent.\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='AFOC-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#form-status').textContent='Your brief is ready. Save it and share it with your AFOC contact. No information has been sent.'});

const products=[
  {name:'ADSS Cables',code:'AFOC / ADSS',label:'AERIAL / SELF-SUPPORTING',lead:'Self-supporting optical cable engineered for aerial distribution, campus loops and medium-to-long span routes.',application:'Aerial outside-plant networks, including deployment along existing rights of way and transmission towers.',construction:'Loose-tube fibers around an FRP central member, reinforced with high-strength aramid yarns and protected by an HDPE jacket.',fibers:'06F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Designed around span length and loading conditions','Lightweight, UV protected and easy to install','Single-mode and multimode fiber options available']},
  {name:'Tight Buffered Cables',code:'AFOC / TBC',label:'INDOOR / OUTDOOR RISER',lead:'A compact, fire-conscious cable for building backbones, telecom rooms and riser pathways.',application:'Indoor and outdoor building networks, especially backbones, telecom-room routes and multi-level riser installations.',construction:'900 μm tight-buffered fibers reinforced with aramid yarns and finished with a Low Smoke Zero Halogen outer sheath.',fibers:'04F / 06F / 12F',length:'1 / 2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Fast field installation with 900 μm tight buffers','Small diameter, lightweight and flexible','LSZH sheath supports higher fire-safety requirements']},
  {name:'FTTH Cables',code:'AFOC / DPC',label:'HOME / OFFICE / LAST LINK',lead:'Flat drop cable designed for the final FTTx connection into homes, apartments and offices.',application:'Indoor FTTx links, riser and plenum distribution, and the connection from the main distribution frame to the final consolidation point.',construction:'One, two or four bend-sensitive fibers protected by parallel FRP strength members inside an LSZH outer jacket.',fibers:'01F / 02F / 04F',length:'500 / 1000 m',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20',features:['Low-bend-sensitive fiber for reliable transmission','Parallel strength members improve crush resistance','Low-smoke, zero-halogen flame-retardant sheath']},
  {name:'Un-Armored Cables',code:'AFOC / UAC',label:'DUCT / OUTSIDE PLANT',lead:'Lightweight loose-tube cable for protected outside-plant routes where flexibility and handling matter.',application:'Outside-plant duct and lashed-aerial environments, installable through pulling, trenching or blowing techniques.',construction:'Loose tubes around an FRP central member with water blocking elements, finished in an HDPE or LSZH single jacket.',fibers:'04F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Tensile and crush resistance','Water-blocking design for protected cable cores','Multiple ripcord configurations for mid-span access']},
  {name:'Armoured Cables',code:'AFOC / AMC',label:'DIRECT BURIAL / DUCT',lead:'Steel-tape protected optical cable for demanding outside-plant routes and direct-burial environments.',application:'Outside-plant duct, direct-burial and lashed-aerial installations where additional mechanical protection is required.',construction:'Loose-tube cable around an FRP member, protected by water-blocking layers, corrugated steel tape armour and an HDPE or LSZH jacket.',fibers:'04F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Steel tape armour adds rodent protection','High tensile and crush resistance','UV protected and engineered for harsh environments']},
  {name:'Micro Duct Cables',code:'AFOC / MDC',label:'ACCESS / METRO / AIR-BLOWN',lead:'Small-diameter optical cable created to place more fiber into existing and new sub-duct networks.',application:'Access and metro networks, including air-blown drop cabling for FTTx deployments.',construction:'Stranded loose tubes around an FRP central member with water-swellable elements, binder yarns and an HDPE or nylon jacket.',fibers:'04F–288F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Smaller diameter helps reduce installation load','Maximizes duct and right-of-way utilization','Lightweight design supports handling and blowing distance']}
];
const productTabs=[...document.querySelectorAll('.product-tab')];
function setProduct(i){
  const p=products[i];
  productTabs.forEach((b,j)=>{b.classList.toggle('is-active',j===i);b.setAttribute('aria-selected',String(j===i));b.tabIndex=j===i?0:-1});
  $('#product-index').textContent=`0${i+1} / 06`;
  $('#product-code').textContent=p.code;
  $('#product-art-label').textContent=p.label;
  $('#product-title').textContent=p.name;
  $('#product-lead').textContent=p.lead;
  $('#product-application').textContent=p.application;
  $('#product-construction').textContent=p.construction;
  $('#product-fibers').textContent=p.fibers;
  $('#product-length').textContent=p.length;
  $('#product-temp').textContent=p.temp;
  $('#product-standards').textContent=p.standards;
  $('#product-features').innerHTML=p.features.map(x=>`<li>${x}</li>`).join('');
  $('#product-brief').dataset.topic=p.name;
}
productTabs.forEach((b,i)=>{b.addEventListener('click',()=>setProduct(i));b.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const dir=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;const n=e.key==='Home'?0:e.key==='End'?products.length-1:(i+dir+products.length)%products.length;setProduct(n);productTabs[n].focus()}})});
setProduct(0);
