
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
document.querySelectorAll('[data-mail]').forEach(el=>{
  el.addEventListener('click',e=>{
    e.preventDefault();
    const topic=el.dataset.topic||'AFOC website enquiry';
    location.href='mailto:sales@arabianfiber.com?subject='+encodeURIComponent('AFOC Enquiry — '+topic);
  });
});
const products=[
{name:'ADSS Cables',code:'AFOC / ADSS',label:'AERIAL / SELF-SUPPORTING',lead:'Self-supporting optical cable engineered for aerial distribution, campus loops and medium-to-long span routes.',application:'Aerial outside-plant networks, including deployment along existing rights of way and transmission towers.',construction:'Loose-tube fibers around an FRP central member, reinforced with high-strength aramid yarns and protected by an HDPE jacket.',fibers:'06F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Designed around span length and loading conditions','Lightweight, UV protected and easy to install','Single-mode and multimode fiber options available']},
{name:'Tight Buffered Cables',code:'AFOC / TBC',label:'INDOOR / OUTDOOR RISER',lead:'A compact, fire-conscious cable for building backbones, telecom rooms and riser pathways.',application:'Indoor and outdoor building networks, especially backbones, telecom-room routes and multi-level riser installations.',construction:'900 μm tight-buffered fibers reinforced with aramid yarns and finished with a Low Smoke Zero Halogen outer sheath.',fibers:'04F / 06F / 12F',length:'1 / 2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Fast field installation with 900 μm tight buffers','Small diameter, lightweight and flexible','LSZH sheath supports higher fire-safety requirements']},
{name:'FTTH Cables',code:'AFOC / DPC',label:'HOME / OFFICE / LAST LINK',lead:'Flat drop cable designed for the final FTTx connection into homes, apartments and offices.',application:'Indoor FTTx links, riser and plenum distribution, and the connection from the main distribution frame to the final consolidation point.',construction:'One, two or four bend-sensitive fibers protected by parallel FRP strength members inside an LSZH outer jacket.',fibers:'01F / 02F / 04F',length:'500 / 1000 m',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20',features:['Low-bend-sensitive fiber for reliable transmission','Parallel strength members improve crush resistance','Low-smoke, zero-halogen flame-retardant sheath']},
{name:'Un-Armored Cables',code:'AFOC / UAC',label:'DUCT / OUTSIDE PLANT',lead:'Lightweight loose-tube cable for protected outside-plant routes where flexibility and handling matter.',application:'Outside-plant duct and lashed-aerial environments, installable through pulling, trenching or blowing techniques.',construction:'Loose tubes around an FRP central member with water blocking elements, finished in an HDPE or LSZH single jacket.',fibers:'04F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Tensile and crush resistance','Water-blocking design for protected cable cores','Multiple ripcord configurations for mid-span access']},
{name:'Armoured Cables',code:'AFOC / AMC',label:'DIRECT BURIAL / DUCT',lead:'Steel-tape protected optical cable for demanding outside-plant routes and direct-burial environments.',application:'Outside-plant duct, direct-burial and lashed-aerial installations where additional mechanical protection is required.',construction:'Loose-tube cable around an FRP member, protected by water-blocking layers, corrugated steel tape armour and an HDPE or LSZH jacket.',fibers:'04F–96F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Steel tape armour adds rodent protection','High tensile and crush resistance','UV protected and engineered for harsh environments']},
{name:'Micro Duct Cables',code:'AFOC / MDC',label:'ACCESS / METRO / AIR-BLOWN',lead:'Small-diameter optical cable created to place more fiber into existing and new sub-duct networks.',application:'Access and metro networks, including air-blown drop cabling for FTTx deployments.',construction:'Stranded loose tubes around an FRP central member with water-swellable elements, binder yarns and an HDPE or nylon jacket.',fibers:'04F–288F',length:'2 / 4 km',temp:'−40°C → +70°C',standards:'ITU-T · IEC 60793/60794 · Telcordia GR-20 · EIA/TIA',features:['Smaller diameter helps reduce installation load','Maximizes duct and right-of-way utilization','Lightweight design supports handling and blowing distance']}
];
const tabs=$$('.product-tab');
function setProduct(i){
 if(!tabs.length)return; const p=products[i];
 tabs.forEach((b,j)=>{b.classList.toggle('is-active',j===i);b.setAttribute('aria-selected',String(j===i))});
 [['#product-index','0'+(i+1)+' / 06'],['#product-code',p.code],['#product-art-label',p.label],['#product-title',p.name],['#product-lead',p.lead],['#product-application',p.application],['#product-construction',p.construction],['#product-fibers',p.fibers],['#product-length',p.length],['#product-temp',p.temp],['#product-standards',p.standards]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v});
 const f=$('#product-features');if(f)f.innerHTML=p.features.map(x=>'<li>'+x+'</li>').join('');
 const b=$('#product-brief');if(b)b.dataset.topic=p.name;
}
tabs.forEach((b,i)=>b.addEventListener('click',()=>setProduct(i))); setProduct(0);
$$('[data-product-jump]').forEach(a=>a.href='products.html');
